#ifndef POSITION_ENUM_H
#define POSITION_ENUM_H

enum Position {
    START,
    FRONT_LEFT,
    FRONT_RIGHT,
    BACK_LEFT,
    BACK_RIGHT,
    MIDDLE_FRONT,
    MIDDLE_BACK,
    NONE,
    ON_LINE_FRONT,
    ON_LINE_FRONT_LEFT,
    ON_LINE_FRONT_RIGHT,
    ON_LINE_BACK,
    ON_LINE_BACK_LEFT,
    ON_LINE_BACK_RIGHT
};

#endif