#ifndef IRSENSORPOSITIONENUM_H
#define IRSENSORPOSITIONENUM_H

enum IRSensorPositionEnum {LEFT_IR_90, LEFT_IR_60, LEFT_IR_45, LEFT_IR_IN, CENTER_IR, RIGHT_IR_IN, RIGHT_IR_45, RIGHT_IR_60, RIGHT_IR_90};

#endif