#ifndef ENEMYPOSITIONENUM_H
#define ENEMYPOSITIONENUM_H

enum EnemyPositionEnum {OP_LEFT_90, OP_LEFT_60, OP_LEFT_45, OP_ON_PLOW, OP_CLOSE_CENTER, OP_FAR_CENTER, OP_RIGHT_45, OP_RIGHT_60, OP_RIGHT_90};

#endif